apiVersion: v1
kind: Pod
metadata:
  labels:
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: webapp
    volumeMounts:
    - name: app-log
      mountPath: /log

  volumes:
  - name: app-log
    persistentVolumeClaim:
      claimName: claim-log-1


